[2016-07-13 22:22:22] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-13 22:22:22] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-13 22:22:22] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-13 22:22:22] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "", null, "", 0, "mz6leh31zm88gosg0w88sssw4gocw8k", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, null, null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, \"\", null, \"\", 0, \"mz6leh31zm88gosg0w88sssw4gocw8k\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, null, null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-07-13 22:22:22] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 01:19:20] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 01:19:20] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 01:19:20] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 01:19:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 2 passed to Monolog\Logger::debug() must be of the type array, object given, called in /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php on line 103 and defined" at /home/zendar/workspaces/SAFE/application/safe_api/app/cache/prod/classes.php line 6556 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 2 passed to Monolog\\Logger::debug() must be of the type array, object given, called in /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php on line 103 and defined at /home/zendar/workspaces/SAFE/application/safe_api/app/cache/prod/classes.php:6556)"} []
[2016-07-14 01:19:20] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 01:22:25] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 01:22:25] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 01:22:25] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 01:22:25] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 113508375 bytes)" at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php line 103 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 113508375 bytes) at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php:103)"} []
[2016-07-14 01:22:25] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 01:23:36] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 01:23:36] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 01:23:36] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 01:23:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 113508415 bytes)" at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php line 103 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 113508415 bytes) at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php:103)"} []
[2016-07-14 01:23:37] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 01:25:20] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 01:25:20] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 01:25:20] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 01:25:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 113508415 bytes)" at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php line 103 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 113508415 bytes) at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Controller/UsuarioController.php:103)"} []
[2016-07-14 01:25:20] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 02:15:19] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 02:15:19] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 02:15:19] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 02:15:20] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "", null, "", 0, "j704pomaaxkcoscsscosgw00gwo4oko", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, null, null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, \"\", null, \"\", 0, \"j704pomaaxkcoscsscosgw00gwo4oko\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, null, null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-07-14 02:15:21] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 02:17:13] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 02:17:13] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 02:17:13] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 02:17:14] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "", null, "", 0, "duo8aojl4d4c8c44cw0k8ck4s8gwwoo", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, null, null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, \"\", null, \"\", 0, \"duo8aojl4d4c8c44cw0k8ck4s8gwwoo\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, null, null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-07-14 02:17:14] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 02:19:29] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 02:19:29] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 02:19:29] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 02:19:29] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "", null, "", 0, "8enn39da3gsock0g0wkggc8cgwkkkwg", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, null, null, null, null]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, \"\", null, \"\", 0, \"8enn39da3gsock0g0wkggc8cgwkkkwg\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, null, null, null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-07-14 02:19:29] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 14:17:44] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 14:17:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 14:28:48] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 14:28:48] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 14:28:48] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 14:28:48] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "AbstractType" from namespace "Safe\PerfilBundle\Form". Did you forget a "use" statement for "Symfony\Component\Form\AbstractType"?" at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Form/UsuarioType.php line 13 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AbstractType\" from namespace \"Safe\\PerfilBundle\\Form\".\nDid you forget a \"use\" statement for \"Symfony\\Component\\Form\\AbstractType\"? at /home/zendar/workspaces/SAFE/application/safe_api/src/Safe/PerfilBundle/Form/UsuarioType.php:13)"} []
[2016-07-14 14:28:48] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 14:53:14] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 14:53:14] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 14:53:14] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 14:53:14] request.CRITICAL: Uncaught PHP Exception Doctrine\Common\Annotations\AnnotationException: "[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_PARENTHESIS, got 'max' at position 200 in method Safe\PerfilBundle\Entity\Usuario::getUsername()." at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php line 42 {"exception":"[object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got 'max' at position 200 in method Safe\\PerfilBundle\\Entity\\Usuario::getUsername(). at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2016-07-14 14:53:14] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 15:16:12] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:16:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 15:44:00] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:44:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 15:46:55] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:46:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 15:47:08] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:47:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 15:47:27] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:47:27] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 15:47:50] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:47:50] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 15:49:08] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:49:08] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 15:49:08] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 15:49:08] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["test1_username", "test1_username", "test1@safe.com", "test1@safe.com", 0, "d7g5ifhxwm8kw04sgkow04co0gc044o", "WXZ8dLHjK7Vbd+WuV9g7+2qmrCMIK9Wd4Oc80ScCI4uLAwukNDACISaRn0Xeeb14M2STCexfx7a6nrU3Ax8Yjw==", null, 0, 0, null, null, null, "a:0:{}", 0, null, "test1_nick", "Test1", "Test1_apellido", null]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8'" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"test1_username\", \"test1_username\", \"test1@safe.com\", \"test1@safe.com\", 0, \"d7g5ifhxwm8kw04sgkow04co0gc044o\", \"WXZ8dLHjK7Vbd+WuV9g7+2qmrCMIK9Wd4Oc80ScCI4uLAwukNDACISaRn0Xeeb14M2STCexfx7a6nrU3Ax8Yjw==\", null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"test1_nick\", \"Test1\", \"Test1_apellido\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8' at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8' at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8' at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-07-14 15:49:08] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 15:51:42] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 15:51:42] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 15:51:42] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 15:51:42] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["test1_username", "test1_username", "test1@safe.com", "test1@safe.com", 0, "av5xed884wg8cwo84woksc0cc8gss84", "PTeCx+TVI9Nehf1Jk0baZ757InqurFuDWH2x68mWY6MElL4vJkwxp2etsshCoSYut92B3PfB6V7pMXYpyZM1qA==", null, 0, 0, null, null, null, "a:0:{}", 0, null, "test1_nick", "Test1", "Test1_apellido", null]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8'" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO usuario (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, nickname, nombre, apellido, avatar) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"test1_username\", \"test1_username\", \"test1@safe.com\", \"test1@safe.com\", 0, \"av5xed884wg8cwo84woksc0cc8gss84\", \"PTeCx+TVI9Nehf1Jk0baZ757InqurFuDWH2x68mWY6MElL4vJkwxp2etsshCoSYut92B3PfB6V7pMXYpyZM1qA==\", null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"test1_nick\", \"Test1\", \"Test1_apellido\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8' at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8' at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test1_username' for key 'UNIQ_2265B05D92FC23A8' at /home/zendar/workspaces/SAFE/application/safe_api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-07-14 15:51:42] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 16:34:06] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 16:34:06] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 16:34:06] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 16:34:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "nickname" nor one of the methods "getNickname()", "nickname()", "isNickname()", "hasNickname()", "__get()" exist and have public access in class "Safe\PerfilBundle\Entity\Usuario"." at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 486 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"nickname\" nor one of the methods \"getNickname()\", \"nickname()\", \"isNickname()\", \"hasNickname()\", \"__get()\" exist and have public access in class \"Safe\\PerfilBundle\\Entity\\Usuario\". at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:486)"} []
[2016-07-14 16:34:06] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 16:34:28] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 16:34:28] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 16:34:28] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 16:34:28] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "nickname" nor one of the methods "getNickname()", "nickname()", "isNickname()", "hasNickname()", "__get()" exist and have public access in class "Safe\PerfilBundle\Entity\Usuario"." at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 486 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"nickname\" nor one of the methods \"getNickname()\", \"nickname()\", \"isNickname()\", \"hasNickname()\", \"__get()\" exist and have public access in class \"Safe\\PerfilBundle\\Entity\\Usuario\". at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:486)"} []
[2016-07-14 16:34:28] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 16:35:19] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 16:35:19] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 16:35:19] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 16:35:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\ConstraintDefinitionException: "The field "nickname" is not mapped by Doctrine, so it cannot be validated for uniqueness." at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php line 85 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\ConstraintDefinitionException(code: 0): The field \"nickname\" is not mapped by Doctrine, so it cannot be validated for uniqueness. at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Validator/Constraints/UniqueEntityValidator.php:85)"} []
[2016-07-14 16:35:19] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 16:48:50] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/app_dev.php"" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/app_dev.php\" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/zendar/workspaces/SAFE/application/safe_api/app/cache/prod/appProdUrlMatcher.php:378)"} []
[2016-07-14 18:41:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/app_dev.php"" at /home/zendar/workspaces/SAFE/application/safe_api/app/cache/prod/classes.php line 2605 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/app_dev.php\" at /home/zendar/workspaces/SAFE/application/safe_api/app/cache/prod/classes.php:2605, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /home/zendar/workspaces/SAFE/application/safe_api/app/cache/prod/appProdUrlMatcher.php:378)"} []
[2016-07-14 19:20:30] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 19:20:30] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 19:20:30] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 19:20:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "[0]": Expected an array." at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 1149 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"[0]\": Expected an array. at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:1149, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Expected an array. at /home/zendar/workspaces/SAFE/application/safe_api/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataTransformer/ChoicesToValuesTransformer.php:49)"} []
[2016-07-14 19:20:30] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 19:25:03] request.INFO: Matched route "api_1_perfilespost_users". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::postUsersAction","_format":"json","_route":"api_1_perfilespost_users"},"request_uri":"http://localhost:8001/api/v1/users.json"} []
[2016-07-14 19:25:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid json message received" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException(code: 0): Invalid json message received at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/BodyListener.php:119)"} []
[2016-07-14 19:27:06] request.INFO: Matched route "api_1_perfilesget_usuarios". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::getUsuariosAction","_format":"html","_route":"api_1_perfilesget_usuarios"},"request_uri":"http://localhost:8001/api/v1/usuarios.html"} []
[2016-07-14 19:27:06] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 19:27:06] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 19:27:06] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The template should be a string or extend TemplateReference" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php line 218 {"exception":"[object] (InvalidArgumentException(code: 0): The template should be a string or extend TemplateReference at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php:218)"} []
[2016-07-14 19:27:06] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
[2016-07-14 19:29:45] request.INFO: Matched route "api_1_perfilesget_usuarios". {"route_parameters":{"_controller":"Safe\\PerfilBundle\\Controller\\UsuarioController::getUsuariosAction","_format":"html","_route":"api_1_perfilesget_usuarios"},"request_uri":"http://localhost:8001/api/v1/usuarios.html"} []
[2016-07-14 19:29:45] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-07-14 19:29:45] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\EmailUserProvider"} []
[2016-07-14 19:29:45] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The template should be a string or extend TemplateReference" at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php line 218 {"exception":"[object] (InvalidArgumentException(code: 0): The template should be a string or extend TemplateReference at /home/zendar/workspaces/SAFE/application/safe_api/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/View/View.php:218)"} []
[2016-07-14 19:29:45] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
